language: python
python:
 - 2.7
# - 3.6
# - "nightly"
# matrix:
#   allow_failures:
#    - python: "nightly"

#sudo: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
env:
  global:
    - MASTER_BRANCH=master
    - PYPI_PY=3.6  # deploy to pypi from python 3.6
  matrix:
    - TEST_DIR=tests/base
    #- TEST_DIR=tests/cyl
    #- TEST_DIR=tests/tree
    #- TEST_DIR=tests/docs

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
       wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
     else
       wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
     fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --quiet --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pillow cython ipython;
  - conda install --quiet --yes -c menpo vtk
  - pip install -r requirements_dev.txt

install:
  - docker pull $DOCKER_IMAGE
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build_wheels.sh
  - pip install discretize --find-links wheelhouse/

script:
  - nosetests $TEST_DIR --with-cov --cov discretize --cov-config .coveragerc -v -s;
