trigger:
  branches:
    include:
    - 'main'
    exclude:
    - '*no-ci*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'

stages:
  - stage: StyleChecks
    displayName: "Style Checks"
    jobs:
      - template: .ci/azure/style.yml

  - stage: Testing
    dependsOn: StyleChecks
    jobs:
      - template: .ci/azure/test.yml

  - stage: DocBuild
    dependsOn: StyleChecks
    jobs:
      - template: .ci/azure/docs.yml

  - stage: BuildWheels
    dependsOn:
      - Testing
      - DocBuild
    displayName: "Build Wheels"
    jobs:
      - template: .ci/azure/wheels.yml

  - stage: BuildSource
    dependsOn:
      - Testing
      - DocBuild
    displayName: "Build Source distribution"
    jobs:
      - template: .ci/azure/sdist.yml

# -----------------------------------------------------------------------------

  - stage: Experiment
    displayName: "Experiment with pipelines (remove this stage)"
    dependsOn:
      - DocBuild
    jobs:
    - job:
      displayName: "Experiment with variable"
      pool:
        vmImage: ubuntu-latest

      # Get stored variables.
      # called "version".
      variables:
        # Get the discretize version used to build the docs in the "DocBuild"
        # stage, "BuildDocs" job, and "discretizeVersion" task. The variable is
        - name: VERSION
          value: $[ stageDependencies.DocBuild.BuildDocs.outputs['discretizeVersion.version'] ]

      steps:
        - bash: |
            echo $VERSION
          displayName: Echo variable
          env:
            VERSION: $(VERSION) # defined in variables section

# -----------------------------------------------------------------------------

  - stage: Deploy
    displayName: "Deploy Source, Wheels, and Docs"
    dependsOn:
      - BuildWheels
      - BuildSource
      - DocBuild
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/'))
    jobs:
      - template: .ci/azure/deploy.yml


