trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'

variables:
  BRANCH_NAME: $(Build.SourceBranchName)
  IS_TAG: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  IS_MAIN: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: StyleChecks
    displayName: "Style Checks"
    jobs:
      - template: .ci/azure/style.yml

  - stage: BuildSource
    displayName: "Build Source distribution"
    jobs:
      - template: .ci/azure/sdist.yml

  - stage: BuildWheels
    displayName: "Build Wheels"
    jobs:
      - template: .ci/azure/wheels.yml

#  - stage: Testing
#    dependsOn: StyleChecks
#    jobs:
#      - template: .ci/azure/test.yml
#
#  - stage: DocBuild
#    dependsOn: StyleChecks
#    jobs:
#      - template: .ci/azure/docs.yml
#
#  - stage: Deploy
#    displayName: "Deploy Source, Wheels, and Docs"
#    dependsOn:
#      - BuildWheels
#      - BuildSource
#    condition: and(succeeded(), or(eq(variables.IS_TAG, true), eq(variables.IS_MAIN, true)))
#    jobs:
#      - template: .ci/azure/deploy.yml


