jobs:
- job:
  displayName: "Build wheels on ${{ variables.image }}"
  strategy:
      matrix:
        linux-Python310:
          image: 'Ubuntu-20.04'
          CIBW_BUILD: 'cp310-*'
        linux-Python311:
          image: 'Ubuntu-20.04'
          CIBW_BUILD: 'cp311-*'
        linux-Python312:
          image: 'Ubuntu-20.04'
          CIBW_BUILD: 'cp312-*'
        osx-Python310:
          image: 'macOS-12'
          CIBW_BUILD: 'cp310-*'
          CIBW_ARCHS_MACOS: 'x86_64 arm64'
        osx-Python311:
          image: 'macOS-12'
          CIBW_BUILD: 'cp311-*'
          CIBW_ARCHS_MACOS: 'x86_64 arm64'
        osx-Python312:
          image: 'macOS-12'
          CIBW_BUILD: 'cp312-*'
          CIBW_ARCHS_MACOS: 'x86_64 arm64'
        win-Python310:
          image: 'windows-2019'
          CIBW_BUILD: 'cp310-*'
          CIBW_ARCHS_WINDOWS: 'AMD64'
          CIBW_CONFIG_SETTINGS: 'setup-args=--vsenv'
        win-Python311:
          image: 'windows-2019'
          CIBW_BUILD: 'cp311-*'
          CIBW_ARCHS_WINDOWS: 'AMD64'
          CIBW_CONFIG_SETTINGS: 'setup-args=--vsenv'
        win-Python312:
          image: 'windows-2019'
          CIBW_BUILD: 'cp312-*'
          CIBW_ARCHS_WINDOWS: 'AMD64'
          CIBW_CONFIG_SETTINGS: 'setup-args=--vsenv'
  pool:
    vmImage: $(image)
  steps:
    # No need to checkout the repo here, were going to build from the source distribution!
    - checkout: none

    - task: UsePythonVersion@0

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'source_dist'
        targetPath: 'dist'

    - bash: |
        source_dist=$(ls dist/*.tar.gz)
        tar --strip-components=1 -xvzf $source_dist
        ls -al
      displayName: Unpack source distribution.

    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==2.20.0
      displayName: Install dependencies

    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'wheelhouse'
        ArtifactName: 'wheels'